package com.oss.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("company", "id", Company.class);
		arp.addMapping("department", "depid", Department.class);
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("left", "leftid", Left.class);
		arp.addMapping("legalman", "legalid", Legalman.class);
		arp.addMapping("stages", "stageid", Stages.class);
		arp.addMapping("statements", "staid", Statements.class);
		arp.addMapping("statistic_analysis_test", "date", StatisticAnalysisTest.class);
		arp.addMapping("stattype_dict", "", StattypeDict.class);
		arp.addMapping("statype", "statid", Statype.class);
//		arp.addMapping("table179", "id", Table179.class);
//		arp.addMapping("table188", "id", Table188.class);
//		arp.addMapping("table189", "id", Table189.class);
//		arp.addMapping("table192", "id", Table192.class);
		arp.addMapping("upper", "uppid", Upper.class);
		arp.addMapping("users", "userid", Users.class);
		arp.addMapping("data_search", "", DataSearch.class);
		arp.addMapping("report_search", "", ReportSearch.class);
	}
}

