package com.oss.model;

import com.oss.basemodel.BaseDataSearch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataSearch extends BaseDataSearch<DataSearch> {
	public static final DataSearch dao = new DataSearch();
}
