package com.oss.model;

import com.oss.basemodel.BaseStages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stages extends BaseStages<Stages> {
	public static final Stages dao = new Stages();
}
