package com.oss.model;

import com.oss.basemodel.BaseStatisticAnalysisTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatisticAnalysisTest extends BaseStatisticAnalysisTest<StatisticAnalysisTest> {
	public static final StatisticAnalysisTest dao = new StatisticAnalysisTest();
}
