package com.oss.model;

import com.oss.basemodel.BaseStattypeDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StattypeDict extends BaseStattypeDict<StattypeDict> {
	public static final StattypeDict dao = new StattypeDict();
}
