package com.oss.model;

import com.oss.basemodel.BaseStatype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statype extends BaseStatype<Statype> {
	public static final Statype dao = new Statype();
}
