package com.oss.model;

import com.oss.basemodel.BaseUpper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Upper extends BaseUpper<Upper> {
	public static final Upper dao = new Upper();
}
