var _depid=parent.$("#user_department").val();
/**
 * 算子添加修改下拉框级联
 */
$(document).ready(function(){
	//算子名
	$("#operatorName").attr("value",$("#_orname").val());
	//选择期数
	$("#orstage").combobox({
		valueField:"orstageid",
		textField:"orstagename",
		value:$("#_orstage").val().toString(),
		data:[{    
		    "orstageid":0,    
		    "orstagename":"本期"   
		},{    
		    "orstageid":1,    
		    "orstagename":"环比"   
		},{    
		    "orstageid":2,    
		    "orstagename":"同比"   
		}]  
		});
	//统计维度
	$("#orstastage").combobox({
		valueField:"orstageid",
		textField:"orstagename",
		value:$("#_orstastage").val().toString(),
		data:[{    
			    "orstageid":"0",    
			    "orstagename":"年"   
			},{    
			    "orstageid":"1",    
			    "orstagename":"季度"   
			},{    
			    "orstageid":"2",    
			    "orstagename":"月"    
			}]  
		});	
	//选择原始报表
	$.ajax({
		type:"post",
		url:"/diyMenu/ListAllHaveLeftAndDataStatement",
		data:{"depid":$("#_statdepartment").val(),
			"type":$("#_stattype").val()
		},
		success:function(res){
			$("#orstatement").combobox({//选择报表
				valueField:"staid",
				textField:"staname",
				value:$("#_orstatement").val().toString(),
				data:res.data,
				onChange:function(newVal,oldVal){
					$.ajax({
						type:"post",
						url:"/diyMenu/getStageAndUpperAndLeft",
						data:{"staid":newVal},
						success:function(resp){
							$("#orupper").combobox({
		        				valueField:"uppid",
		        				textField:"uppstruct",
		        				data:resp.data.upperList
		        			});
							$("#orupper").combobox('clear');
							$("#orleft").combobox({
		        				valueField:"leftid",
		        				textField:"leftstruct",
		        				data:resp.data.leftList
		        			});
							$("#orleft").combobox('clear');
						}
					});
					$.ajax({
						type:"post",
						url:"/diyMenu/getStagename",
						data:{"staid":newVal},
						success:function(resp){
							$("#orstagename").combobox({
		        				valueField:"stagename",
		        				textField:"stagename",
		        				value:resp.data[0].stagename,
		        				data:resp.data
		        			});
							$("#orstagename").combobox('clear');
						}
					});
				}
			});
		}
	});
	//报表类型
	$.ajax({
		type:"post",
		url:"/diyMenu/findStatementType",
		data:{
			"depid":$("#_statdepartment").val()
		},
		success:function(re){
			$("#stattype").combobox({
				valueField:"stattype",
				textField:"typename",
				data:re,
				value:$("#_stattype").val().toString(),
				onChange:function(newType,oldType){
					$("#orstagename").combobox("clear");
					$("#orstagename").combobox('loadData', {});
					$("#orupper").combobox("clear");
					$("#orupper").combobox('loadData', {});
					$("#orleft").combobox("clear");
					$("#orleft").combobox('loadData', {});
					var newDep = $("#department").combobox("getValue");
					$.ajax({
						type:"post",
						url:"/diyMenu/ListAllHaveLeftAndDataStatement",
						data:{"depid":newDep,
						"type":newType
						},
						success:function(res){
							$("#orstatement").combobox({
		        				valueField:"staid",
		        				textField:"staname",
		        				value:"",
		        				data:res.data,
		        				onChange:function(newVal,oldVal){
		        					$.ajax({
		        						type:"post",
		        						url:"/diyMenu/getStageAndUpperAndLeft",
		        						data:{"staid":newVal},
		        						success:function(resp){
		        							$("#orupper").combobox({
		        		        				valueField:"uppid",
		        		        				textField:"uppstruct",
		        		        				data:resp.data.upperList
		        		        			});
		        							$("#orupper").combobox('clear');
		        							$("#orleft").combobox({
		        		        				valueField:"leftid",
		        		        				textField:"leftstruct",
		        		        				data:resp.data.leftList
		        		        			});
		        							$("#orleft").combobox('clear');
		        						}
		        					});
		        					$.ajax({
		        						type:"post",
		        						url:"/diyMenu/getStagename",
		        						data:{"staid":newVal},
		        						success:function(resp){
		        							$("#orstagename").combobox({
		        		        				valueField:"stagename",
		        		        				textField:"stagename",
		        		        				value:resp.data[0].stagename,
		        		        				data:resp.data
		        		        			});
		        							$("#orstagename").combobox('clear');
		        						}
		        					});
		        				}
							});
							$("#orstatement").combobox("clear");
						}
					});
				}
			});
		}
	});
	
	$.ajax({
		type:"post",
		url:"/diyMenu/getStageAndUpperAndLeft",
		data:{"staid":$("#_orstatement").val()},
		success:function(resp){
			$("#orupper").combobox({
				valueField:"uppid",
				textField:"uppstruct",
				value:$("#_orupper").val().toString(),
				data:resp.data.upperList
			});
			$("#orleft").combobox({
				valueField:"leftid",
				textField:"leftstruct",
				value:$("#_orleft").val().toString(),
				data:resp.data.leftList
			});
		}
	});
	
	$.ajax({//选择地区名
		type:"post",
		url:"/diyMenu/getStagename",
		data:{"staid":$("#_orstatement").val()},
		success:function(resp){
			$("#orstagename").combobox({
				valueField:"stagename",
				textField:"stagename",
				value:$("#_orstagename").val().toString(),
				data:resp.data
			});
		}
	});
	
	$.ajax({
		type:"post",
		url:"/department/ListDepartment",
		success: function(result){
			$("#ordepartment").combobox({//算子所属部门
				valueField:"depid",
				textField:"depname",
				value:$("#_ordepartment").val().toString(),
				data:result.data
			});
			$("#department").combobox({//原始报表所属部门
				valueField:"depid",
				textField:"depname",
				value:$("#_statdepartment").val(),
				data:result.data,
				onChange:function(newDep,oldDep){
					$.ajax({
						type:"post",
						url:"/diyMenu/findStatementType",
						data:{
							"depid":newDep
						},
						success:function(re){
							$("#orstatement").combobox("clear");
							$("#orstatement").combobox('loadData', {});
							$("#orstagename").combobox("clear");
							$("#orstagename").combobox('loadData', {});
							$("#orupper").combobox("clear");
							$("#orupper").combobox('loadData', {});
							$("#orleft").combobox("clear");
							$("#orleft").combobox('loadData', {});
							$("#stattype").combobox({
								valueField:"stattype",
								textField:"typename",
								data:re,
								onChange:function(newType,oldType){
									$.ajax({
										type:"post",
										url:"/diyMenu/ListAllHaveLeftAndDataStatement",
										data:{"depid":newDep,
										"type":newType
										},
										success:function(res){
											$("#orstatement").combobox({
						        				valueField:"staid",
						        				textField:"staname",
						        				data:res.data,
						        				onChange:function(newVal,oldVal){						  
						        					$.ajax({
						        						type:"post",
						        						url:"/diyMenu/getStageAndUpperAndLeft",
						        						data:{"staid":newVal},
						        						success:function(resp){
						        							$("#orupper").combobox({
						        		        				valueField:"uppid",
						        		        				textField:"uppstruct",
						        		        				data:resp.data.upperList
						        		        			});
						        							$("#orupper").combobox('clear');
						        							$("#orleft").combobox({
						        		        				valueField:"leftid",
						        		        				textField:"leftstruct",
						        		        				data:resp.data.leftList
						        		        			});
						        							$("#orleft").combobox('clear');
						        						}
						        					});
						        					$.ajax({
						        						type:"post",
						        						url:"/diyMenu/getStagename",
						        						data:{"staid":newVal},
						        						success:function(resp){
						        							$("#orstagename").combobox({
						        		        				valueField:"stagename",
						        		        				textField:"stagename",
						        		        				value:resp.data[0].stagename,
						        		        				data:resp.data
						        		        			});
						        							$("#orstagename").combobox('clear');
						        						}
						        					});
						        				}
											});
											$("#orstatement").combobox('clear');
										}
									});
								}
							});
							$("#stattype").combobox("clear");
						}
					});
				}
			});
		}
	});
if(_depid!=0){
	$("#ordepartment").next(".combo").hide();
	$("#label_ordepartment").hide();//如果是部门管理者要隐藏选择算子所属部门，给算子所属部门一个固定的id
}
});

function submitForm(){
	$("#updateOperator").form({
		url:"/derive/editOperator",
		onSubmit:function(param){
			if(_depid!=0){
				param.ordepartment=_depid;
			}
			param.orid=$("#_orid").val();
			var stattype = $("#stattype").combobox('getValue');//报表类型(0-年报,1-半年报,2-季报,3-月报,4-常规报表)
			var orstastage = $("#orstastage").combobox('getValue');//统计维度(0-年,1-季度,2-月)
//			console.log(stattype+"==="+orstastage);
			if((stattype==0&&(orstastage==1||orstastage==2))||(stattype==2&&orstastage==2)){
				layer.msg("统计维度不能小于报表类型");
				return false;
			}
		},
		success:function(resp){
//			layer.msg(JSON.stringify(resp),{time:10000000000000});
			if(eval('('+resp+')').resultCode=="0"){
				layer.msg("修改成功",{time:1000});
				setTimeout(function(){parent.$('#mydialog').dialog('close');},2000);
//				parent.$('#mydialog').dialog('close');
			}else{
				layer.msg(eval('('+resp+')').resultDesc);
				setTimeout(function(){parent.$('#mydialog').dialog('close');},2000);
			}
		}
	});
	$("#updateOperator").submit();
}

function cancelForm(){
	parent.$('#mydialog').dialog('close');
}
