package com.oss.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("company", "ogrnumber", Company.class);
		arp.addMapping("company_history", "", CompanyHistory.class);
		arp.addMapping("company_temp", "", CompanyTemp.class);
		arp.addMapping("deheader", "deheadid", Deheader.class);
		arp.addMapping("department", "depid", Department.class);
		arp.addMapping("derivestatement", "deid", Derivestatement.class);
		arp.addMapping("dict_import_record", "uuid", DictImportRecord.class);
		arp.addMapping("dictionary", "code", Dictionary.class);
		arp.addMapping("dictionary_history", "", DictionaryHistory.class);
		arp.addMapping("dictionary_temp", "", DictionaryTemp.class);
		arp.addMapping("formula", "faid", Formula.class);
		arp.addMapping("left", "leftid", Left.class);
		arp.addMapping("left1", "leftid", Left1.class);
		arp.addMapping("legalman", "ogrcode", Legalman.class);
		arp.addMapping("legalman_history", "", LegalmanHistory.class);
		arp.addMapping("legalman_temp", "", LegalmanTemp.class);
		arp.addMapping("operator", "orid", Operator.class);
		arp.addMapping("reformula", "refid", Reformula.class);
		arp.addMapping("reheader", "reheadid", Reheader.class);
		arp.addMapping("rules", "id", Rules.class);
		arp.addMapping("rulestatement", "reid", Rulestatement.class);
		arp.addMapping("stages", "stageid", Stages.class);
		arp.addMapping("statements", "staid", Statements.class);
		arp.addMapping("stattype_dict", "", StattypeDict.class);
		arp.addMapping("statype", "statid", Statype.class);
		arp.addMapping("test", "id", Test.class);
		arp.addMapping("upper", "uppid", Upper.class);
		arp.addMapping("users", "userid", Users.class);
		arp.addMapping("assets_invest", "", AssetsInvest.class);
		arp.addMapping("industy_increase", "", IndustyIncrease.class);
		arp.addMapping("major_ecomomic_view", "", MajorEcomomicView.class);
		arp.addMapping("operator_view", "", OperatorView.class);
		arp.addMapping("regionalgdp", "", Regionalgdp.class);
		arp.addMapping("report_search", "", ReportSearch.class);
		arp.addMapping("revenues", "", Revenues.class);
		arp.addMapping("social_spend", "", SocialSpend.class);
		arp.addMapping("statements_view", "", StatementsView.class);
		arp.addMapping("urban_per", "", UrbanPer.class);
		arp.addMapping("village_per", "", VillagePer.class);
	}
}

