package com.oss.model;

import com.oss.basemodel.BaseAssetsInvest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AssetsInvest extends BaseAssetsInvest<AssetsInvest> {
	public static final AssetsInvest dao = new AssetsInvest();
}
