package com.oss.model;

import com.oss.basemodel.BaseCompanyHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyHistory extends BaseCompanyHistory<CompanyHistory> {
	public static final CompanyHistory dao = new CompanyHistory();
}
