package com.oss.model;

import com.oss.basemodel.BaseCompanyTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyTemp extends BaseCompanyTemp<CompanyTemp> {
	public static final CompanyTemp dao = new CompanyTemp();
}
