package com.oss.model;

import com.oss.basemodel.BaseDatatabletest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Datatabletest extends BaseDatatabletest<Datatabletest> {
	public static final Datatabletest dao = new Datatabletest();
}
