package com.oss.model;

import com.oss.basemodel.BaseDeheader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deheader extends BaseDeheader<Deheader> {
	public static final Deheader dao = new Deheader();
}
