package com.oss.model;

import com.oss.basemodel.BaseDeleft;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deleft extends BaseDeleft<Deleft> {
	public static final Deleft dao = new Deleft();
}
