package com.oss.model;

import com.oss.basemodel.BaseDeriveupper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deriveupper extends BaseDeriveupper<Deriveupper> {
	public static final Deriveupper dao = new Deriveupper();
}
