package com.oss.model;

import com.oss.basemodel.BaseDerivestatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Derivestatement extends BaseDerivestatement<Derivestatement> {
	public static final Derivestatement dao = new Derivestatement();
}
