package com.oss.model;

import com.oss.basemodel.BaseDictImportRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictImportRecord extends BaseDictImportRecord<DictImportRecord> {
	public static final DictImportRecord dao = new DictImportRecord();
}
