package com.oss.model;

import com.oss.basemodel.BaseDictionaryTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictionaryTemp extends BaseDictionaryTemp<DictionaryTemp> {
	public static final DictionaryTemp dao = new DictionaryTemp();
}
