package com.oss.model;

import com.oss.basemodel.BaseDictionaryHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictionaryHistory extends BaseDictionaryHistory<DictionaryHistory> {
	public static final DictionaryHistory dao = new DictionaryHistory();
}
