package com.oss.model;

import com.oss.basemodel.BaseFormula;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Formula extends BaseFormula<Formula> {
	public static final Formula dao = new Formula();
}
