package com.oss.model;

import com.oss.basemodel.BaseIndustyIncrease;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IndustyIncrease extends BaseIndustyIncrease<IndustyIncrease> {
	public static final IndustyIncrease dao = new IndustyIncrease();
}
