package com.oss.model;

import com.oss.basemodel.BaseLeft;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Left extends BaseLeft<Left> {
	public static final Left dao = new Left();
}
