package com.oss.model;

import com.oss.basemodel.BaseLeft1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Left1 extends BaseLeft1<Left1> {
	public static final Left1 dao = new Left1();
}
