package com.oss.model;

import com.oss.basemodel.BaseLegalmanTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LegalmanTemp extends BaseLegalmanTemp<LegalmanTemp> {
	public static final LegalmanTemp dao = new LegalmanTemp();
}
