package com.oss.model;

import com.oss.basemodel.BaseLegalman;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Legalman extends BaseLegalman<Legalman> {
	public static final Legalman dao = new Legalman();
}
