package com.oss.model;

import com.oss.basemodel.BaseLegalmanHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LegalmanHistory extends BaseLegalmanHistory<LegalmanHistory> {
	public static final LegalmanHistory dao = new LegalmanHistory();
}
