package com.oss.model;

import com.oss.basemodel.BaseMajorEcomomicView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MajorEcomomicView extends BaseMajorEcomomicView<MajorEcomomicView> {
	public static final MajorEcomomicView dao = new MajorEcomomicView();
}
