package com.oss.model;

import com.oss.basemodel.BaseOperatorView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperatorView extends BaseOperatorView<OperatorView> {
	public static final OperatorView dao = new OperatorView();
}
