package com.oss.model;

import com.oss.basemodel.BaseOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operator extends BaseOperator<Operator> {
	public static final Operator dao = new Operator();
}
