package com.oss.model;

import com.oss.basemodel.BaseOrstage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orstage extends BaseOrstage<Orstage> {
	public static final Orstage dao = new Orstage();
}
