package com.oss.model;

import com.oss.basemodel.BaseReformula;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reformula extends BaseReformula<Reformula> {
	public static final Reformula dao = new Reformula();
}
