package com.oss.model;

import com.oss.basemodel.BaseRegionalgdp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Regionalgdp extends BaseRegionalgdp<Regionalgdp> {
	public static final Regionalgdp dao = new Regionalgdp();
}
