package com.oss.model;

import com.oss.basemodel.BaseReheader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reheader extends BaseReheader<Reheader> {
	public static final Reheader dao = new Reheader();
}
