package com.oss.model;

import com.oss.basemodel.BaseReportSearch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportSearch extends BaseReportSearch<ReportSearch> {
	public static final ReportSearch dao = new ReportSearch();
}
