package com.oss.model;

import com.oss.basemodel.BaseRevenues;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Revenues extends BaseRevenues<Revenues> {
	public static final Revenues dao = new Revenues();
}
