package com.oss.model;

import com.oss.basemodel.BaseRulestatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rulestatement extends BaseRulestatement<Rulestatement> {
	public static final Rulestatement dao = new Rulestatement();
}
