package com.oss.model;

import com.oss.basemodel.BaseRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rules extends BaseRules<Rules> {
	public static final Rules dao = new Rules();
}
