package com.oss.model;

import com.oss.basemodel.BaseSocialSpend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SocialSpend extends BaseSocialSpend<SocialSpend> {
	public static final SocialSpend dao = new SocialSpend();
}
