package com.oss.model;

import com.oss.basemodel.BaseStatements;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statements extends BaseStatements<Statements> {
	public static final Statements dao = new Statements();
}
