package com.oss.model;

import com.oss.basemodel.BaseStatementsView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatementsView extends BaseStatementsView<StatementsView> {
	public static final StatementsView dao = new StatementsView();
}
