package com.oss.model;

import com.oss.basemodel.BaseTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	public static final Test dao = new Test();
}
