package com.oss.model;

import com.oss.basemodel.BaseUrbanPer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UrbanPer extends BaseUrbanPer<UrbanPer> {
	public static final UrbanPer dao = new UrbanPer();
}
