package com.oss.model;

import com.oss.basemodel.BaseVillagePer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VillagePer extends BaseVillagePer<VillagePer> {
	public static final VillagePer dao = new VillagePer();
}
