package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDatatabletest<M extends BaseDatatabletest<M>> extends Model<M> implements IBean {

	public void setDataid(java.math.BigInteger dataid) {
		set("dataid", dataid);
	}

	public java.math.BigInteger getDataid() {
		return get("dataid");
	}

	public void setLeftid(java.lang.Integer leftid) {
		set("leftid", leftid);
	}

	public java.lang.Integer getLeftid() {
		return get("leftid");
	}

}
