package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatisticAnalysisTest<M extends BaseStatisticAnalysisTest<M>> extends Model<M> implements IBean {

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setCount(java.lang.String count) {
		set("count", count);
	}

	public java.lang.String getCount() {
		return get("count");
	}

	public void setNormal(java.lang.String normal) {
		set("normal", normal);
	}

	public java.lang.String getNormal() {
		return get("normal");
	}

	public void setAdd(java.lang.String add) {
		set("add", add);
	}

	public java.lang.String getAdd() {
		return get("add");
	}

	public void setChange(java.lang.String change) {
		set("change", change);
	}

	public java.lang.String getChange() {
		return get("change");
	}

}
