package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setUserpass(java.lang.String userpass) {
		set("userpass", userpass);
	}

	public java.lang.String getUserpass() {
		return get("userpass");
	}

	public void setUserdepartment(java.lang.Integer userdepartment) {
		set("userdepartment", userdepartment);
	}

	public java.lang.Integer getUserdepartment() {
		return get("userdepartment");
	}

	public void setUsertype(java.lang.Integer usertype) {
		set("usertype", usertype);
	}

	public java.lang.Integer getUsertype() {
		return get("usertype");
	}

	public void setUserstate(java.lang.Integer userstate) {
		set("userstate", userstate);
	}

	public java.lang.Integer getUserstate() {
		return get("userstate");
	}

	public void setUserdepartmentsStr(java.lang.String userdepartmentsStr) {
		set("userdepartments_str", userdepartmentsStr);
	}

	public java.lang.String getUserdepartmentsStr() {
		return get("userdepartments_str");
	}

}
