package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDerivestatement<M extends BaseDerivestatement<M>> extends Model<M> implements IBean {

	public void setDeid(java.lang.Long deid) {
		set("deid", deid);
	}

	public java.lang.Long getDeid() {
		return get("deid");
	}

	public void setDename(java.lang.String dename) {
		set("dename", dename);
	}

	public java.lang.String getDename() {
		return get("dename");
	}

	public void setDetype(java.lang.Integer detype) {
		set("detype", detype);
	}

	public java.lang.Integer getDetype() {
		return get("detype");
	}

	public void setDedepartment(java.lang.Integer dedepartment) {
		set("dedepartment", dedepartment);
	}

	public java.lang.Integer getDedepartment() {
		return get("dedepartment");
	}

	public void setDetime(java.util.Date detime) {
		set("detime", detime);
	}

	public java.util.Date getDetime() {
		return get("detime");
	}

	public void setDerow(java.lang.Integer derow) {
		set("derow", derow);
	}

	public java.lang.Integer getDerow() {
		return get("derow");
	}

	public void setDecol(java.lang.Integer decol) {
		set("decol", decol);
	}

	public java.lang.Integer getDecol() {
		return get("decol");
	}

}
