package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUpper<M extends BaseUpper<M>> extends Model<M> implements IBean {

	public void setUppid(java.lang.Integer uppid) {
		set("uppid", uppid);
	}

	public java.lang.Integer getUppid() {
		return get("uppid");
	}

	public void setUppfieldname(java.lang.String uppfieldname) {
		set("uppfieldname", uppfieldname);
	}

	public java.lang.String getUppfieldname() {
		return get("uppfieldname");
	}

	public void setUppstruct(java.lang.String uppstruct) {
		set("uppstruct", uppstruct);
	}

	public java.lang.String getUppstruct() {
		return get("uppstruct");
	}

	public void setUppstatement(java.lang.Integer uppstatement) {
		set("uppstatement", uppstatement);
	}

	public java.lang.Integer getUppstatement() {
		return get("uppstatement");
	}

	public void setUppshow(java.lang.Integer uppshow) {
		set("uppshow", uppshow);
	}

	public java.lang.Integer getUppshow() {
		return get("uppshow");
	}

	public void setUppdatatype(java.lang.Integer uppdatatype) {
		set("uppdatatype", uppdatatype);
	}

	public java.lang.Integer getUppdatatype() {
		return get("uppdatatype");
	}

	public void setUppcid(java.lang.Integer uppcid) {
		set("uppcid", uppcid);
	}

	public java.lang.Integer getUppcid() {
		return get("uppcid");
	}

	public void setUppcreatetime(java.util.Date uppcreatetime) {
		set("uppcreatetime", uppcreatetime);
	}

	public java.util.Date getUppcreatetime() {
		return get("uppcreatetime");
	}

	public void setUppdeletetime(java.util.Date uppdeletetime) {
		set("uppdeletetime", uppdeletetime);
	}

	public java.util.Date getUppdeletetime() {
		return get("uppdeletetime");
	}

}
