package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMajorEcomomicView<M extends BaseMajorEcomomicView<M>> extends Model<M> implements IBean {

	public void setYear(java.lang.Integer year) {
		set("year", year);
	}

	public java.lang.Integer getYear() {
		return get("year");
	}

	public void set地区生产总值(java.lang.String 地区生产总值) {
		set("地区生产总值", 地区生产总值);
	}

	public java.lang.String get地区生产总值() {
		return get("地区生产总值");
	}

	public void set比上年增长1(java.lang.String 比上年增长1) {
		set("比上年增长1", 比上年增长1);
	}

	public java.lang.String get比上年增长1() {
		return get("比上年增长1");
	}

	public void set第一产业(java.lang.String 第一产业) {
		set("第一产业", 第一产业);
	}

	public java.lang.String get第一产业() {
		return get("第一产业");
	}

	public void set比上年增长2(java.lang.String 比上年增长2) {
		set("比上年增长2", 比上年增长2);
	}

	public java.lang.String get比上年增长2() {
		return get("比上年增长2");
	}

	public void set第二产业(java.lang.String 第二产业) {
		set("第二产业", 第二产业);
	}

	public java.lang.String get第二产业() {
		return get("第二产业");
	}

	public void set比上年增长3(java.lang.String 比上年增长3) {
		set("比上年增长3", 比上年增长3);
	}

	public java.lang.String get比上年增长3() {
		return get("比上年增长3");
	}

	public void set第三产业(java.lang.String 第三产业) {
		set("第三产业", 第三产业);
	}

	public java.lang.String get第三产业() {
		return get("第三产业");
	}

	public void set比上年增长4(java.lang.String 比上年增长4) {
		set("比上年增长4", 比上年增长4);
	}

	public java.lang.String get比上年增长4() {
		return get("比上年增长4");
	}

	public void set人均地区生产总值(java.lang.String 人均地区生产总值) {
		set("人均地区生产总值", 人均地区生产总值);
	}

	public java.lang.String get人均地区生产总值() {
		return get("人均地区生产总值");
	}

	public void set比上年增长5(java.lang.String 比上年增长5) {
		set("比上年增长5", 比上年增长5);
	}

	public java.lang.String get比上年增长5() {
		return get("比上年增长5");
	}

	public void set固定资产投资(java.lang.String 固定资产投资) {
		set("固定资产投资", 固定资产投资);
	}

	public java.lang.String get固定资产投资() {
		return get("固定资产投资");
	}

	public void set比上年增长6(java.lang.String 比上年增长6) {
		set("比上年增长6", 比上年增长6);
	}

	public java.lang.String get比上年增长6() {
		return get("比上年增长6");
	}

	public void set规模以上工业增加值(java.lang.String 规模以上工业增加值) {
		set("规模以上工业增加值", 规模以上工业增加值);
	}

	public java.lang.String get规模以上工业增加值() {
		return get("规模以上工业增加值");
	}

	public void set比上年增长7(java.lang.String 比上年增长7) {
		set("比上年增长7", 比上年增长7);
	}

	public java.lang.String get比上年增长7() {
		return get("比上年增长7");
	}

	public void set公共财政预算收入(java.lang.String 公共财政预算收入) {
		set("公共财政预算收入", 公共财政预算收入);
	}

	public java.lang.String get公共财政预算收入() {
		return get("公共财政预算收入");
	}

	public void set比上年增长8(java.lang.String 比上年增长8) {
		set("比上年增长8", 比上年增长8);
	}

	public java.lang.String get比上年增长8() {
		return get("比上年增长8");
	}

	public void set地方公共财政预算收入(java.lang.String 地方公共财政预算收入) {
		set("地方公共财政预算收入", 地方公共财政预算收入);
	}

	public java.lang.String get地方公共财政预算收入() {
		return get("地方公共财政预算收入");
	}

	public void set比上年增长9(java.lang.String 比上年增长9) {
		set("比上年增长9", 比上年增长9);
	}

	public java.lang.String get比上年增长9() {
		return get("比上年增长9");
	}

	public void set公共财政预算支出(java.lang.String 公共财政预算支出) {
		set("公共财政预算支出", 公共财政预算支出);
	}

	public java.lang.String get公共财政预算支出() {
		return get("公共财政预算支出");
	}

	public void set比上年增长10(java.lang.String 比上年增长10) {
		set("比上年增长10", 比上年增长10);
	}

	public java.lang.String get比上年增长10() {
		return get("比上年增长10");
	}

	public void set城镇常住居民人均可支配收入(java.lang.String 城镇常住居民人均可支配收入) {
		set("城镇常住居民人均可支配收入", 城镇常住居民人均可支配收入);
	}

	public java.lang.String get城镇常住居民人均可支配收入() {
		return get("城镇常住居民人均可支配收入");
	}

	public void set比上年增长11(java.lang.String 比上年增长11) {
		set("比上年增长11", 比上年增长11);
	}

	public java.lang.String get比上年增长11() {
		return get("比上年增长11");
	}

	public void set农村常住居民人均可支配收入(java.lang.String 农村常住居民人均可支配收入) {
		set("农村常住居民人均可支配收入", 农村常住居民人均可支配收入);
	}

	public java.lang.String get农村常住居民人均可支配收入() {
		return get("农村常住居民人均可支配收入");
	}

	public void set比上年增长12(java.lang.String 比上年增长12) {
		set("比上年增长12", 比上年增长12);
	}

	public java.lang.String get比上年增长12() {
		return get("比上年增长12");
	}

	public void set社会消费品零售总额(java.lang.String 社会消费品零售总额) {
		set("社会消费品零售总额", 社会消费品零售总额);
	}

	public java.lang.String get社会消费品零售总额() {
		return get("社会消费品零售总额");
	}

	public void set比上年增长13(java.lang.String 比上年增长13) {
		set("比上年增长13", 比上年增长13);
	}

	public java.lang.String get比上年增长13() {
		return get("比上年增长13");
	}

}
