package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReheader<M extends BaseReheader<M>> extends Model<M> implements IBean {

	public void setReheadid(java.lang.Long reheadid) {
		set("reheadid", reheadid);
	}

	public java.lang.Long getReheadid() {
		return get("reheadid");
	}

	public void setReheadname(java.lang.String reheadname) {
		set("reheadname", reheadname);
	}

	public java.lang.String getReheadname() {
		return get("reheadname");
	}

	public void setReheadstatement(java.lang.Long reheadstatement) {
		set("reheadstatement", reheadstatement);
	}

	public java.lang.Long getReheadstatement() {
		return get("reheadstatement");
	}

	public void setReheadlocation(java.lang.String reheadlocation) {
		set("reheadlocation", reheadlocation);
	}

	public java.lang.String getReheadlocation() {
		return get("reheadlocation");
	}

	public void setReheadrowspan(java.lang.Integer reheadrowspan) {
		set("reheadrowspan", reheadrowspan);
	}

	public java.lang.Integer getReheadrowspan() {
		return get("reheadrowspan");
	}

	public void setReheadcolspan(java.lang.Integer reheadcolspan) {
		set("reheadcolspan", reheadcolspan);
	}

	public java.lang.Integer getReheadcolspan() {
		return get("reheadcolspan");
	}

}
