package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeleft<M extends BaseDeleft<M>> extends Model<M> implements IBean {

	public void setDeleftid(java.lang.Long deleftid) {
		set("deleftid", deleftid);
	}

	public java.lang.Long getDeleftid() {
		return get("deleftid");
	}

	public void setDeleftname(java.lang.String deleftname) {
		set("deleftname", deleftname);
	}

	public java.lang.String getDeleftname() {
		return get("deleftname");
	}

	public void setDeleftstruct(java.lang.String deleftstruct) {
		set("deleftstruct", deleftstruct);
	}

	public java.lang.String getDeleftstruct() {
		return get("deleftstruct");
	}

	public void setDeleftrow(java.lang.Integer deleftrow) {
		set("deleftrow", deleftrow);
	}

	public java.lang.Integer getDeleftrow() {
		return get("deleftrow");
	}

	public void setDeleftstatement(java.lang.Long deleftstatement) {
		set("deleftstatement", deleftstatement);
	}

	public java.lang.Long getDeleftstatement() {
		return get("deleftstatement");
	}

	public void setDeleftcreatetime(java.util.Date deleftcreatetime) {
		set("deleftcreatetime", deleftcreatetime);
	}

	public java.util.Date getDeleftcreatetime() {
		return get("deleftcreatetime");
	}

}
