package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRules<M extends BaseRules<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRestate(java.lang.Long restate) {
		set("restate", restate);
	}

	public java.lang.Long getRestate() {
		return get("restate");
	}

	public void setRestaid(java.lang.Integer restaid) {
		set("restaid", restaid);
	}

	public java.lang.Integer getRestaid() {
		return get("restaid");
	}

	public void setReupper(java.lang.Integer reupper) {
		set("reupper", reupper);
	}

	public java.lang.Integer getReupper() {
		return get("reupper");
	}

	public void setReconstraint(java.lang.String reconstraint) {
		set("reconstraint", reconstraint);
	}

	public java.lang.String getReconstraint() {
		return get("reconstraint");
	}

	public void setRetype(java.lang.Integer retype) {
		set("retype", retype);
	}

	public java.lang.Integer getRetype() {
		return get("retype");
	}

	public void setRetimespan(java.lang.Integer retimespan) {
		set("retimespan", retimespan);
	}

	public java.lang.Integer getRetimespan() {
		return get("retimespan");
	}

	public void setReposition(java.lang.Integer reposition) {
		set("reposition", reposition);
	}

	public java.lang.Integer getReposition() {
		return get("reposition");
	}

}
