package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReformula<M extends BaseReformula<M>> extends Model<M> implements IBean {

	public void setRefid(java.lang.Long refid) {
		set("refid", refid);
	}

	public java.lang.Long getRefid() {
		return get("refid");
	}

	public void setRestate(java.lang.Long restate) {
		set("restate", restate);
	}

	public java.lang.Long getRestate() {
		return get("restate");
	}

	public void setReflocation(java.lang.String reflocation) {
		set("reflocation", reflocation);
	}

	public java.lang.String getReflocation() {
		return get("reflocation");
	}

	public void setRefcontent(java.lang.String refcontent) {
		set("refcontent", refcontent);
	}

	public java.lang.String getRefcontent() {
		return get("refcontent");
	}

}
