package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeriveupper<M extends BaseDeriveupper<M>> extends Model<M> implements IBean {

	public void setDeupper(java.lang.Long deupper) {
		set("deupper", deupper);
	}

	public java.lang.Long getDeupper() {
		return get("deupper");
	}

	public void setDeuppername(java.lang.String deuppername) {
		set("deuppername", deuppername);
	}

	public java.lang.String getDeuppername() {
		return get("deuppername");
	}

	public void setDeupperstruct(java.lang.String deupperstruct) {
		set("deupperstruct", deupperstruct);
	}

	public java.lang.String getDeupperstruct() {
		return get("deupperstruct");
	}

	public void setDestatement(java.lang.Long destatement) {
		set("destatement", destatement);
	}

	public java.lang.Long getDestatement() {
		return get("destatement");
	}

	public void setDeuppcol(java.lang.Integer deuppcol) {
		set("deuppcol", deuppcol);
	}

	public java.lang.Integer getDeuppcol() {
		return get("deuppcol");
	}

	public void setUppcreatetime(java.util.Date uppcreatetime) {
		set("uppcreatetime", uppcreatetime);
	}

	public java.util.Date getUppcreatetime() {
		return get("uppcreatetime");
	}

}
