package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrstage<M extends BaseOrstage<M>> extends Model<M> implements IBean {

	public void setOrseid(java.lang.Integer orseid) {
		set("orseid", orseid);
	}

	public java.lang.Integer getOrseid() {
		return get("orseid");
	}

	public void setOrsename(java.lang.String orsename) {
		set("orsename", orsename);
	}

	public java.lang.String getOrsename() {
		return get("orsename");
	}

}
