package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictionary<M extends BaseDictionary<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setIssue(java.lang.String issue) {
		set("issue", issue);
	}

	public java.lang.String getIssue() {
		return get("issue");
	}

	public void setMajor(java.lang.String major) {
		set("major", major);
	}

	public java.lang.String getMajor() {
		return get("major");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setDetailname(java.lang.String detailname) {
		set("detailname", detailname);
	}

	public java.lang.String getDetailname() {
		return get("detailname");
	}

	public void setLegal(java.lang.String legal) {
		set("legal", legal);
	}

	public java.lang.String getLegal() {
		return get("legal");
	}

	public void setAreacode(java.lang.String areacode) {
		set("areacode", areacode);
	}

	public java.lang.String getAreacode() {
		return get("areacode");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setActivity(java.lang.String activity) {
		set("activity", activity);
	}

	public java.lang.String getActivity() {
		return get("activity");
	}

	public void setTradecode(java.lang.String tradecode) {
		set("tradecode", tradecode);
	}

	public java.lang.String getTradecode() {
		return get("tradecode");
	}

	public void setTradename(java.lang.String tradename) {
		set("tradename", tradename);
	}

	public java.lang.String getTradename() {
		return get("tradename");
	}

	public void setRegister(java.lang.String register) {
		set("register", register);
	}

	public java.lang.String getRegister() {
		return get("register");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setOrgtype(java.lang.String orgtype) {
		set("orgtype", orgtype);
	}

	public java.lang.String getOrgtype() {
		return get("orgtype");
	}

	public void setActivitynumber(java.lang.String activitynumber) {
		set("activitynumber", activitynumber);
	}

	public java.lang.String getActivitynumber() {
		return get("activitynumber");
	}

	public void setIndustryyear(java.lang.String industryyear) {
		set("industryyear", industryyear);
	}

	public java.lang.String getIndustryyear() {
		return get("industryyear");
	}

	public void setIndustrymonth(java.lang.String industrymonth) {
		set("industrymonth", industrymonth);
	}

	public java.lang.String getIndustrymonth() {
		return get("industrymonth");
	}

	public void setBuildyear(java.lang.String buildyear) {
		set("buildyear", buildyear);
	}

	public java.lang.String getBuildyear() {
		return get("buildyear");
	}

	public void setBuildmonth(java.lang.String buildmonth) {
		set("buildmonth", buildmonth);
	}

	public java.lang.String getBuildmonth() {
		return get("buildmonth");
	}

	public void setServiceyear(java.lang.String serviceyear) {
		set("serviceyear", serviceyear);
	}

	public java.lang.String getServiceyear() {
		return get("serviceyear");
	}

	public void setTradeyear(java.lang.String tradeyear) {
		set("tradeyear", tradeyear);
	}

	public java.lang.String getTradeyear() {
		return get("tradeyear");
	}

	public void setTradecertain(java.lang.String tradecertain) {
		set("tradecertain", tradecertain);
	}

	public java.lang.String getTradecertain() {
		return get("tradecertain");
	}

	public void setLabouryear(java.lang.String labouryear) {
		set("labouryear", labouryear);
	}

	public java.lang.String getLabouryear() {
		return get("labouryear");
	}

	public void setLabourcertain(java.lang.String labourcertain) {
		set("labourcertain", labourcertain);
	}

	public java.lang.String getLabourcertain() {
		return get("labourcertain");
	}

	public void setEstateyear(java.lang.String estateyear) {
		set("estateyear", estateyear);
	}

	public java.lang.String getEstateyear() {
		return get("estateyear");
	}

	public void setEstatecertain(java.lang.String estatecertain) {
		set("estatecertain", estatecertain);
	}

	public java.lang.String getEstatecertain() {
		return get("estatecertain");
	}

	public void setCateryear(java.lang.String cateryear) {
		set("cateryear", cateryear);
	}

	public java.lang.String getCateryear() {
		return get("cateryear");
	}

	public void setCatercertain(java.lang.String catercertain) {
		set("catercertain", catercertain);
	}

	public java.lang.String getCatercertain() {
		return get("catercertain");
	}

	public void setEnvironmentyear(java.lang.String environmentyear) {
		set("environmentyear", environmentyear);
	}

	public java.lang.String getEnvironmentyear() {
		return get("environmentyear");
	}

	public void setEnvironmentcertain(java.lang.String environmentcertain) {
		set("environmentcertain", environmentcertain);
	}

	public java.lang.String getEnvironmentcertain() {
		return get("environmentcertain");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setCurrentime(java.util.Date currentime) {
		set("currentime", currentime);
	}

	public java.util.Date getCurrentime() {
		return get("currentime");
	}

}
