package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataSearch<M extends BaseDataSearch<M>> extends Model<M> implements IBean {

	public void setStageid(java.lang.Integer stageid) {
		set("stageid", stageid);
	}

	public java.lang.Integer getStageid() {
		return get("stageid");
	}

	public void setStaname(java.lang.String staname) {
		set("staname", staname);
	}

	public java.lang.String getStaname() {
		return get("staname");
	}

	public void setStattype(java.lang.Integer stattype) {
		set("stattype", stattype);
	}

	public java.lang.Integer getStattype() {
		return get("stattype");
	}

	public void setStagename(java.lang.String stagename) {
		set("stagename", stagename);
	}

	public java.lang.String getStagename() {
		return get("stagename");
	}

	public void setStagetime(java.util.Date stagetime) {
		set("stagetime", stagetime);
	}

	public java.util.Date getStagetime() {
		return get("stagetime");
	}

	public void setYear(java.lang.Integer year) {
		set("year", year);
	}

	public java.lang.Integer getYear() {
		return get("year");
	}

	public void setMonth(java.lang.Integer month) {
		set("month", month);
	}

	public java.lang.Integer getMonth() {
		return get("month");
	}

	public void setSeason(java.lang.Integer season) {
		set("season", season);
	}

	public java.lang.Integer getSeason() {
		return get("season");
	}

	public void setHalfyear(java.lang.Integer halfyear) {
		set("halfyear", halfyear);
	}

	public java.lang.Integer getHalfyear() {
		return get("halfyear");
	}

	public void setNormal(java.util.Date normal) {
		set("normal", normal);
	}

	public java.util.Date getNormal() {
		return get("normal");
	}

}
