package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRulestatement<M extends BaseRulestatement<M>> extends Model<M> implements IBean {

	public void setReid(java.lang.Long reid) {
		set("reid", reid);
	}

	public java.lang.Long getReid() {
		return get("reid");
	}

	public void setRename(java.lang.String rename) {
		set("rename", rename);
	}

	public java.lang.String getRename() {
		return get("rename");
	}

	public void setRetype(java.lang.Integer retype) {
		set("retype", retype);
	}

	public java.lang.Integer getRetype() {
		return get("retype");
	}

	public void setRedepartment(java.lang.Integer redepartment) {
		set("redepartment", redepartment);
	}

	public java.lang.Integer getRedepartment() {
		return get("redepartment");
	}

	public void setRetime(java.util.Date retime) {
		set("retime", retime);
	}

	public java.util.Date getRetime() {
		return get("retime");
	}

	public void setRerow(java.lang.Integer rerow) {
		set("rerow", rerow);
	}

	public java.lang.Integer getRerow() {
		return get("rerow");
	}

	public void setRecol(java.lang.Integer recol) {
		set("recol", recol);
	}

	public java.lang.Integer getRecol() {
		return get("recol");
	}

}
