package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeheader<M extends BaseDeheader<M>> extends Model<M> implements IBean {

	public void setDeheadid(java.lang.Long deheadid) {
		set("deheadid", deheadid);
	}

	public java.lang.Long getDeheadid() {
		return get("deheadid");
	}

	public void setDeheadname(java.lang.String deheadname) {
		set("deheadname", deheadname);
	}

	public java.lang.String getDeheadname() {
		return get("deheadname");
	}

	public void setDeheadstatement(java.lang.Long deheadstatement) {
		set("deheadstatement", deheadstatement);
	}

	public java.lang.Long getDeheadstatement() {
		return get("deheadstatement");
	}

	public void setDeheadlocation(java.lang.String deheadlocation) {
		set("deheadlocation", deheadlocation);
	}

	public java.lang.String getDeheadlocation() {
		return get("deheadlocation");
	}

	public void setDeheadrowspan(java.lang.Integer deheadrowspan) {
		set("deheadrowspan", deheadrowspan);
	}

	public java.lang.Integer getDeheadrowspan() {
		return get("deheadrowspan");
	}

	public void setDeheadcolspan(java.lang.Integer deheadcolspan) {
		set("deheadcolspan", deheadcolspan);
	}

	public java.lang.Integer getDeheadcolspan() {
		return get("deheadcolspan");
	}

}
