package com.oss.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLegalmanHistory<M extends BaseLegalmanHistory<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setStage(java.lang.String stage) {
		set("stage", stage);
	}

	public java.lang.String getStage() {
		return get("stage");
	}

	public void setOgrcode(java.lang.String ogrcode) {
		set("ogrcode", ogrcode);
	}

	public java.lang.String getOgrcode() {
		return get("ogrcode");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLegelperson(java.lang.String legelperson) {
		set("legelperson", legelperson);
	}

	public java.lang.String getLegelperson() {
		return get("legelperson");
	}

	public void setAreanumber(java.lang.String areanumber) {
		set("areanumber", areanumber);
	}

	public java.lang.String getAreanumber() {
		return get("areanumber");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setAreacode(java.lang.String areacode) {
		set("areacode", areacode);
	}

	public java.lang.String getAreacode() {
		return get("areacode");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setIndustrycode(java.lang.String industrycode) {
		set("industrycode", industrycode);
	}

	public java.lang.String getIndustrycode() {
		return get("industrycode");
	}

	public void setActivity(java.lang.String activity) {
		set("activity", activity);
	}

	public java.lang.String getActivity() {
		return get("activity");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}

	public java.lang.String getYear() {
		return get("year");
	}

	public void setMonth(java.lang.String month) {
		set("month", month);
	}

	public java.lang.String getMonth() {
		return get("month");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setStatisticcode(java.lang.String statisticcode) {
		set("statisticcode", statisticcode);
	}

	public java.lang.String getStatisticcode() {
		return get("statisticcode");
	}

	public void setCurrenttime(java.util.Date currenttime) {
		set("currenttime", currenttime);
	}

	public java.util.Date getCurrenttime() {
		return get("currenttime");
	}

}
